import { Opportunity } from '@/types';

export const mockOpportunities: Opportunity[] = [
  {
    id: 'OPP-2025-001',
    name: '광명전기 2공장 LED',
    type: '3자간',
    energyUser: '(주)광명전기',
    manager: '김민준',
    status: 'APPROVED',
    createdAt: '2025-01-15',
    description: '2공장 조명 에너지 절감 사업',
  },
  {
    id: 'OPP-2025-002',
    name: '인천물류 ESS 도입',
    type: '3자간',
    energyUser: '인천물류(주)',
    manager: '이서연',
    status: 'REVIEWING',
    createdAt: '2025-02-10',
    description: '물류센터 ESS 설치 사업',
  },
  {
    id: 'OPP-2025-003',
    name: '대전시청 BEMS',
    type: '용역',
    energyUser: '대전광역시',
    manager: '박지훈',
    status: 'PO_REQUESTED',
    createdAt: '2025-03-01',
    description: '건물에너지관리시스템 구축',
  },
  {
    id: 'OPP-2025-004',
    name: '삼성전자 태양광',
    type: '용역',
    energyUser: '삼성전자(주)',
    manager: '최수빈',
    status: 'DRAFT',
    createdAt: '2025-03-15',
    description: '사업장 태양광 설치',
  },
  {
    id: 'OPP-2025-005',
    name: '현대차 냉동공조',
    type: '3자간',
    energyUser: '현대자동차(주)',
    manager: '정다은',
    status: 'CONTRACTED',
    createdAt: '2025-01-20',
    description: '공조시스템 에너지 절감',
  },
];
